//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S8__Complet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analytical
    {
        public int ID { get; set; }
        public int IdPred { get; set; }
        public Nullable<double> Result { get; set; }
    
        public virtual Prediction Prediction { get; set; }
    }

    public partial class Donnees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donnees()
        {
            this.Prediction = new HashSet<Prediction>();
        }

        public int ID { get; set; }
        public string DataName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prediction> Prediction { get; set; }
    }

    public partial class Prediction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prediction()
        {
            this.Analytical = new HashSet<Analytical>();
            this.KNN = new HashSet<KNN>();
            this.LogisticRegression = new HashSet<LogisticRegression>();
            this.RandomForest = new HashSet<RandomForest>();
        }

        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int IdData { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analytical> Analytical { get; set; }
        public virtual Donnees Donnees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KNN> KNN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogisticRegression> LogisticRegression { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandomForest> RandomForest { get; set; }
    }

    public partial class KNN
    {
        public int ID { get; set; }
        public string Algorithm { get; set; }
        public string Metric { get; set; }
        public int Nneighbors { get; set; }
        public string Weights { get; set; }
        public int IdPred { get; set; }
        public Nullable<double> Result { get; set; }

        public virtual Prediction Prediction { get; set; }
    }

    public partial class LogisticRegression
    {
        public int ID { get; set; }
        public string Penalty { get; set; }
        public int C { get; set; }
        public string Solver { get; set; }
        public int IdPred { get; set; }
        public Nullable<double> Result { get; set; }

        public virtual Prediction Prediction { get; set; }
    }

    public partial class RandomForest
    {
        public int ID { get; set; }
        public int Nestimator { get; set; }
        public int MaxDepth { get; set; }
        public int IdPred { get; set; }
        public Nullable<double> Result { get; set; }

        public virtual Prediction Prediction { get; set; }
    }
}
