//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S8__Complet.Models
{
    using System;
    using System.Collections.Generic;

    public partial class KNN
    {
        public int ID { get; set; }
        public string Algorithm { get; set; }
        public string Metric { get; set; }
        public int Nneighbors { get; set; }
        public string Weights { get; set; }
        public int IdPred { get; set; }
        public Nullable<double> Result { get; set; }

        public virtual Prediction Prediction { get; set; }
    }
}
